FROM rust:1.75

RUN rustup target add wasm32-unknown-unknown
RUN cargo install --locked --version 21.0.0 soroban-cli

WORKDIR /contract
COPY contract/ .

RUN cargo build --target wasm32-unknown-unknown --release

CMD ["cp", "target/wasm32-unknown-unknown/release/kumbara_contract.wasm", "/output/"]
